- docs/maintainer/README.md
> Remove outdated 'Hasura' link

- Jenkinsfile
- hasura/migrations/metadata.json
- src/__test__/TestApolloServer.ts
- src/buildHasuraSchema.ts
- src/index.ts
- src/resolvers/hasura_resolvers.ts
- src/resolvers/index.ts
Aligns the query interface between the Hasura derived schema and the Cardano GraphQL schema. Closes #161
> Remove query name translation

- Jenkinsfile
- jest.config.js
- package.json
- src/__test__/e2e_client.ts
- src/buildHasuraSchema.ts
- yarn.lock
- Remove the verbose uncontrollable logging, appearing at runtime and during tests
- Explicitly exit the process when the Hasura connection validation fails 
Closes #165
> Repaces promise-exponential-backoff with p-retry, and gracefully handle process exit

- nix/nixos/cardano-graphql-service.nix
- release.nix
Fixes a broken path introduced in https://github.com/input-output-hk/cardano-graphql/pull/200
> Fix hasura path regression with nixos service

- README.md
https://github.com/input-output-hk/cardano-graphql/pull/210#pullrequestreview-442816075
> fix query example

- packages/api-cardano-db-hasura/package.json
- packages/cli/package.json
- packages/client-ts/package.json
- packages/server/package.json
- packages/util-dev/package.json
- packages/util/package.json
Makes it locally available to the npm script required in the npm release pipeline
> Add shx as local devDependency to each package

- packages/api-cardano-db-hasura/hasura/project/migrations/1594274227099_slot_within_epoch_update/down.sql
- packages/api-cardano-db-hasura/hasura/project/migrations/1594274227099_slot_within_epoch_update/up.sql
> fix(hasura): replaces protocol constant calculation with new meta field

- nix/nixos/graphql-engine-service.nix
https://hasura.io/docs/1.0/graphql/manual/guides/telemetry.html
> chore(nixos): disable Hasura telemetry in nixos service

- Dockerfile
Also separates the download and script execution into a separate step for added isolation with the runtime container.
_Note: This vulnerability is not present in the [current release](https://github.com/input-output-hk/cardano-graphql/blob/1.0.0/Dockerfile), and is therefore not considered to require a security advisory_
Closes #227
> fix(cardano-graphql-server): specify TLS protocol in Dockerfile curl to prevent TLS downgrade attack

- packages/api-genesis/schema.graphql
- packages/api-genesis/test/genesis.query.test.ts
also removes unused scalars and a stray console log
> fix(api-genesis): corrects valid nullable fields in the genesis model

- docker-compose.yml
- package.json
- packages/api-genesis/schema.graphql
- packages/api-genesis/src/example_queries/allInfo.graphql
- packages/api-genesis/src/example_queries/keyNetworkInfo.graphql
- packages/api-genesis/test/__snapshots__/genesis.query.test.ts.snap
- packages/server/src/index.ts
- packages/server/test/Server.test.ts
No Byron genesis at this stage, but the nesting means the API will not break when added
> chore: nest Shelley genesis to formalise the era

- packages/server/src/Server.ts
- packages/server/src/config.ts
- packages/server/test/Server.test.ts
Moves configuration logic into `Server` and corrects the correlation between introspection and allow list.
This refactor results in a simple mapping of ENVs to `Config`, and will be easier to add a CLI as an alternative interface.
> test: adds tests and refactors to move config logic into the Server

- packages/api-cardano-db-hasura/hasura/docker-entrypoint.sh
Just a minor change to make that environment variable to be customizable like the others are :)
> Add custom $SECRET_DIR support for docker image

- package.json
- packages/api-cardano-db-hasura/package.json
- packages/api-genesis/package.json
- packages/cli/package.json
- packages/client-ts/package.json
- packages/server/package.json
- packages/util-dev/package.json
- packages/util/package.json
> release 2.2.0-beta

- docker-compose.yml
- packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/test/__snapshots__/epochs.query.test.ts.snap
- packages/api-cardano-db-hasura/test/data_assertions/epoch_assertions.ts
Includes minimal compatibility updates, and corrected assertion
> chore: bump cardano-db-sync

- packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/example_queries/active_stake/averageActiveStakeForAddress.graphql
- packages/api-cardano-db-hasura/src/executableSchema.ts
- packages/api-cardano-db-hasura/test/activeStake.query.test.ts
Closes #345
Att the top-level query
> feature: add top-level activeStake_aggregate query

- packages/cli/src/Docker/DockerComposeStack.ts
- packages/cli/src/Docker/services.ts
> fix: add stateful service definition for cardano-db-sync in the CLI

- .versionrc
- CHANGELOG.md
- docker-compose.yml
- package.json
- packages/api-cardano-db-hasura/package.json
- packages/cli/README.md
- packages/cli/package.json
- packages/client-ts/package.json
- packages/server/package.json
- packages/util-dev/package.json
- packages/util/package.json
> Release 3.0.0 version bump and changelog

- Dockerfile
- nix/graphql-engine/hs-overlay.nix
- nix/hasura-cli-ext/impure.nix
- nix/packages.nix
- packages/api-cardano-db-hasura/hasura/Dockerfile
Upgrading _hasura_ to latest release.
> hasura: 1.3.2 -> 1.3.3

- CHANGELOG.md
- docker-compose.yml
- package.json
- packages/api-cardano-db-hasura/package.json
- packages/cli/package.json
- packages/client-ts/package.json
- packages/server/package.json
- packages/util-dev/package.json
- packages/util/package.json
> Release 3.0.1

- packages/api-cardano-db-hasura/src/executableSchema.ts
- packages/api-cardano-db-hasura/test/__snapshots__/transactions.query.test.ts.snap
- packages/api-cardano-db-hasura/test/transactions.query.test.ts
Fixes #389
Use the `JSONResolver` without changing the type name, to avoid a breaking change.
> fix: JSON resolver for transaction metadata

- docker-compose.dev.yml
- docker-compose.yml
> chore: bump cardano-node and cardano-db-sync versions

- .github/workflows/post_release.yml
> ci: fix post-release workflow docs path

- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/test/activeStake.query.test.ts
> fix: ActiveStake.stakePoolHash field name

- packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
- packages/api-cardano-db-hasura/src/example_queries/epochs/aggregateDataWithinEpoch.graphql
- packages/api-cardano-db-hasura/test/epochs.query.test.ts
> refactor: replace SQL sub-queries with joins

- packages/api-cardano-db-hasura/src/HasuraClient.ts
The error handler is not aligned with the expected error under exception conditions.
Guard against null value and throw expected error
> fix: guards on missing current epoch row

- packages/api-cardano-db-hasura/schema.graphql
> feature: add TransactionOutput_bool_exp.index

- Dockerfile
_Reason for the change? If an issue exists, reference it here using a [keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)_
> remove `mkdir /node-ipc` in Dockerfile

- packages/api-cardano-db-hasura/schema.graphql
> feature: `TransactionInput_order_by.transaction`

- packages/server/src/config.ts
> fix: make METADATA_SERVER_URI required config

- nix/nixos/cardano-graphql-service.nix
- nix/nixos/graphql-engine-service.nix
Merge nixos hotfix done on `6-2-stable`.
> Nixos services fixes

- docker-compose.yml
- `cardano-node@1.35.3-rc1`
- `ogmios@v5.5.3`
- `cardano-db-syns@13.0.4-rc1`
> chore: bump cardano service deps

- docker-compose.yml
- packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
- Duplicate index removed in 471d9ae9177c4f936d8d2e2f267a59739c7d53fa
> Chore/bump cardano service deps + remove duplicate DB index

- packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
Increase performance of `StakePoolOwner` & `Cardano` views
> refactor: optimize Cardano & StakePoolOwner views

- flake.lock
- flake.nix
- nix/cells/automation/hydraJobs.nix
- nix/cells/automation/pipelines.nix
- nix/cells/cloud/actions.nix
- nix/cells/cloud/library.nix
- release.nix
Also purified nix evaluation of hydra jobs.
> add std flake and tullia

- packages/api-cardano-db-hasura/hasura/project/migrations/default/1589369664961_init/up.sql
Fixing a bug which hindered hasura migrations.
> fix: fixing a syntax error in migration file

- .github/workflows/ci.yml
_Reason for the change? If an issue exists, reference it here using a [keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)_
> Update ci.yml - update the ubuntu version to 24.04

- packages/server/src/apollo_server_plugins/prometheus_metrics_plugin.ts
Closes #917
Simply update content-type when sending a response for the metrics endpoint.
Non
> fix: update header on prometheus
