cardano-foundation/cardano-graphql

- src/__test__/data_assertions/block_assertions.ts
- src/__test__/tests/blocks.query.test.ts
- src/schema.graphql
Fixes #91  This is a workaround due to the storage of epoch data not being optimised
> Add Block.epochNo for better perf

- Jenkinsfile
- hasura/Dockerfile
- test/postgres/Dockerfile
1. Removes the development Docker images for Hasura and PostgreSQL, that are currently being used as a convenience to provide a test stack for applications such as Cardano Explorer. The supported approach moving forward is to reference this git repo directly using git submodules for the test data, passing it into the official images [in the same way we do here internally](https://github.com/input-output-hk/cardano-graphql/blob/develop/docker/docker-compose.service-deps.yml). 
2. Docker images are now pushed to https://hub.docker.com/repository/docker/inputoutput/cardano-graphql, now including legally named branches such as `develop` or `master`, and new version tags matching `v*`
> Docker deployment upgrade

- Jenkinsfile
- cli/package.json
- cli/yarn.lock
- generated_packages/TypeScript/package.json
This PR fixes a mis-configuration with the npm lifecycle hooks that resulted in attempts to transpile TS after install. The `pack` lifecycle phase is now targeted to ensure this is only performed when the package is being created.
> Hotfixes TypeScript package postinstall script

- src/schema.graphql
This fixes a backwards compatibility issue where Transaction Fee used to be a string but in GraphQL was set to be a BigInt!. Changing this to String means it passes our data parity tests.
> Change Transaction Fee from BigInt! -> String!

- src/schema.graphql
This reverts commit fb71a5de as per https://github.com/input-output-hk/cardano-graphql/pull/149#issuecomment-618265874
> Revert "Change Transaction Fee from BigInt! -> String! (#149)"

- nix/nixos/cardano-graphql-service.nix
Wiped database and everything broke. In the process of renaming back the base Uri we lost the /v1/query on the metadata import. This adds it back.
> fix metadata import url

- src/__test__/dataparitytests/blocks.parity.test.ts
- src/__test__/dataparitytests/epochs.parity.test.ts
- src/__test__/dataparitytests/index.ts
- src/__test__/dataparitytests/transactions.parity.test.ts
- src/__test__/util.ts
Add data parity tests for epochs. 
Refactored transaction tests to reduce amount of API calls.
> Add data parity tests for epoch details

- hasura/project/metadata/tables.yaml
- hasura/project/migrations/1589369664961_init/up.sql
- package.json
- src/__test__/__snapshots__/suite.test.ts.snap
- src/__test__/data_assertions/transaction_assertions.ts
- src/__test__/tests/transactions.query.test.ts
- src/example_queries/transactions/transactionsByHashesOrderByFee.graphql
- src/schema.graphql
Closes #182 by removing the index field as per discussion in https://github.com/input-output-hk/cardano-db-sync/issues/106
Also removes the additional `Coin` model, as the added abstraction here is unnecessary, and imposes a variation with the Hasura model.
> Remove TransactionInput.index and Coin type

- docker-compose.yml
I am migrating [Adascan.net](https://adascan.net/) to use new graphql api. Last night website died because of docker log file grew to 46G, eating all space on the server. So logs for docker services should be limited by default in docker-compose.yml file
> Set size for docker logs

- Jenkinsfile
- packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/example_queries/utxos/utxoSetForAddress.graphql
- packages/api-cardano-db-hasura/test/blocks.query.test.ts
- packages/api-cardano-db-hasura/test/cardano.query.test.ts
- packages/api-cardano-db-hasura/test/epochs.query.test.ts
- packages/api-cardano-db-hasura/test/graphql_operations/getAnyUtxoAddress.graphql
- packages/api-cardano-db-hasura/test/transactions.query.test.ts
- packages/api-cardano-db-hasura/test/util.ts
- packages/api-cardano-db-hasura/test/utxos.query.test.ts
- packages/cli/test/util.ts
Reimplements #196 due to master branch divergence, which supersedes #195 (Thanks @mebassett)
Includes:
- input -> transaction
- input -> source transaction (where it was an output)
- output -> transaction
**_and_** expressions to use in filtering and sorting.
> Establish relationships to easily access transaction and block information from inputs and outputs

- packages/api-cardano-db-hasura/package.json
- packages/cli/package.json
- packages/server/package.json
- packages/util-dev/package.json
- packages/util/package.json
This is only needed for this implementation of yarn2nix, as yarn workspaces symlinks the bins usually.
> Localise devDeps required by npm scripts

- packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
- packages/api-cardano-db-hasura/hasura/project/migrations/1594274227099_hfc_compat_slot_in_epoch/down.sql
- packages/api-cardano-db-hasura/hasura/project/migrations/1594274227099_hfc_compat_slot_in_epoch/up.sql
- packages/api-cardano-db-hasura/hasura/project/migrations/1594274227099_slot_within_epoch_update/up.sql
- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/Db.ts
- packages/api-cardano-db-hasura/src/example_queries/blocks/blocksByHashes.graphql
- packages/api-cardano-db-hasura/src/example_queries/cardano/static.graphql
- packages/api-cardano-db-hasura/test/__snapshots__/cardano.query.test.ts.snap
- packages/api-cardano-db-hasura/test/data_assertions/block_assertions.ts
- packages/api-cardano-db-hasura/test/dataparitytests/epochs.parity.test.ts
- packages/server/test/app_with_graphql_operations/src/feature_1/cardanoDynamic.graphql
- packages/server/test/app_with_graphql_operations/src/feature_2/cardanoStatic.graphql
- packages/util-dev/src/e2e_client.ts
Breaking changes required for supporting HFC-mode networks, so this is the first of the 2.0 changes.
- fix(api-cardano-db-hasura): align API with domain term 
- chore(api-cardano-db-hasura): remove obsolete values in a HFC-mode chain
> HFC-mode compatibility 

- docker-compose.yml
cardano-node + cardano-db-sync updates pinning versions running the Shelley testnet.
Closes #230 
https://github.com/input-output-hk/cardano-node/commit/83ba7dba184d3634af78e2879013cf4cc99227d1
https://github.com/input-output-hk/cardano-db-sync/commit/74b329d63c876f8e9fd774e09e071c546cf76980
> chore(dependencies): bump service deps for Shelley testnet compat

- nix/packages.nix
- nix/sources.json
- shell.nix
The goal of this PR is to:
* Make `cardano-cli` a dependency of the project
* Provide `cardano-cli` in the nix-shell
* Provide `cardano-cli` on the $PATH for node apps
> [SRE-129] add cardano-cli

- CHANGELOG.md
- docker-compose.yml
- package.json
- packages/api-cardano-db-hasura/package.json
- packages/api-genesis/README.md
- packages/api-genesis/package.json
- packages/cli/package.json
- packages/client-ts/package.json
- packages/server/package.json
- packages/util-dev/package.json
- packages/util/package.json
Closes #24 
Closes #205 
Closes #223
```
PASS test/transactions.query.test.ts (9.165 s)
PASS test/blocks.query.test.ts (9.164 s)
PASS test/epochs.query.test.ts (9.764 s)
PASS test/cardano.query.test.ts
PASS test/utxos.query.test.ts (25.784 s)
Test Suites: 5 passed, 5 total
Tests:       21 passed, 21 total
Snapshots:   13 passed, 13 total
Time:        36.323 s
```
```
PASS test/Server.test.ts (29.109 s)
Server
Whitelisting
Booting the server without providing a whitelist
✓ returns data for all valid queries (98 ms)
Providing a whitelist produced by persistgraphql, intended to limit the API for specific application requirements
✓ Accepts listed queries (14186 ms)
✓ Returns a networkError if a valid but unlisted operation is sent (10470 ms)
Test Suites: 1 passed, 1 total
Tests:       3 …
```
> Version 2.0.0-beta.0

- CHANGELOG.md
- docker-compose.yml
- packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
- packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/example_queries/blocks/blocksByHashes.graphql
- packages/api-cardano-db-hasura/test/data_assertions/block_assertions.ts
Updates to `cardano-db-sync@3.1.0`, restoring `Block.slotInEpoch`
> Chore/cardano db sync 3.1.0 update

- nix/nixos/cardano-graphql-service.nix
We need `POSTGRES_PORT` as a string.
> nixos: POSTGRES_PORT to string

- nix/nixos/cardano-graphql-service.nix
Adds defaults (unix socket and pg_hba auth instead of passwords) that match postgres connection pattern used widely throughout nixpkgs nixos modules.
> nixos service: fix database credentials to work correctly

- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/example_queries/delegations/delegationSample.graphql
- packages/api-cardano-db-hasura/test/delegations.query.test.ts
Hasura is configured with the transaction relationship, however it is not defined in the GraphQL APIs
> fix: add missing GraphQL model for Delegation.transaction

- Dockerfile
- docker-compose.yml
Closes #260 
- Add Dockerfile build `ARG`, defaulting to `mainnet`
- Mounting genesis files for `mainnet` or `testnet` is now a build time concern, although custom network config can still be mounted at runtime.
- Genesis files are now nested in a top level `config` dir in the container
> feat: Add build arg to include genesis files

- docker-compose.yml
- packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
- packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/down.sql
- packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
The current state is targeting `4.0.0`. Upstream indices have also been dropped.
Updates to the `cardano-db-sync` RC, and adopts orphaned indices from https://github.com/input-output-hk/cardano-db-sync/pull/261
- Requires db rebuild
- Targets `cardano-node@1.19.1`
> Chore/cardano db sync 5.0.0

- packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
- packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/example_queries/blocks/aggregateDataWithinBlock.graphql
- packages/api-cardano-db-hasura/src/example_queries/transactions/aggregateDataWithinTransaction.graphql
- packages/api-cardano-db-hasura/src/example_queries/transactions/orderedTransactionsInBlock.graphql
- packages/api-cardano-db-hasura/src/example_queries/transactions/transactionsByHashesOrderByFee.graphql
- packages/api-cardano-db-hasura/test/__snapshots__/blocks.query.test.ts.snap
- packages/api-cardano-db-hasura/test/__snapshots__/transactions.query.test.ts.snap
- packages/api-cardano-db-hasura/test/data_assertions/block_assertions.ts
- packages/api-cardano-db-hasura/test/data_assertions/transaction_assertions.ts
Transaction deposits were added to the `cardano-db-sync` schema
Maps the column through to a field `Transaction.deposit`, and includes relevant filtering options
> feat(api-cardano-db-hasura): add Transaction.deposit

- packages/server/src/express_middleware/allow_list.ts
Closes #303
Scope the allow list logic to the graphql path to so that the metrics endpoint isn't impacted by the allow-list logic
> fix: scope allow list to graphql path

- packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
- packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/example_queries/epochs/aggregateDataWithinEpoch.graphql
- packages/api-cardano-db-hasura/src/example_queries/epochs/epochDetailsByNumber.graphql
- packages/api-cardano-db-hasura/src/example_queries/epochs/epochDetailsInRange.graphql
- packages/api-cardano-db-hasura/src/example_queries/epochs/numberOfBlocksProducedByLeaderInEpoch.graphql
- packages/api-cardano-db-hasura/test/__snapshots__/epochs.query.test.ts.snap
- packages/api-cardano-db-hasura/test/data_assertions/epoch_assertions.ts
Epoch fees were added to the `cardano-db-sync` schema
Maps the column through to a field `Epoch.fees`, and includes relevant filtering options
> feat(api-cardano-db-hasura): add Epoch.fees

- packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
The `StakePool` view is currently excluding pools without a metadata hash included.
Fix the SQL View
> fix: include pools without metadata in StakePool view

- packages/api-cardano-db-hasura/package.json
- packages/server/package.json
When using the api packages in another project, some `@types` packages were missing, and required manual installation.
Adds the missing dev packages to the relevant workspace packages
> fix: include @types/* packages in workspace devDependencies

- packages/api-cardano-db-hasura/schema.graphql
Two sort fields in the GraphQL schema have comparison types associated.
Replace with `order_by` type
> fix: address ordering type mismatch in GraphQL schema

- packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/example_queries/transactions/transactionsByHashesOrderByFee.graphql
- packages/api-cardano-db-hasura/test/__snapshots__/transactions.query.test.ts.snap
- packages/api-cardano-db-hasura/test/data_assertions/transaction_assertions.ts
- packages/api-cardano-db-hasura/test/transactions.query.test.ts
Withdrawals are currently disconnected from the context of a Transaction, despite being part of the [Shelley transaction model](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/shelley-spec-ledger-test/cddl-files/shelley.cddl#L57). It should be natural to implement https://github.com/input-output-hk/cardano-explorer-app/issues/352 
Makes withdrawals and withdrawal aggregate data available from
Transaction, to be easily referenced from the natural context.
Also adds hash as a sort option to transactions and blocks.
> feat(api-cardano-db-hasura): add Transaction.withdrawals

- packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
- packages/api-cardano-db-hasura/schema.graphql
Fixes #328 #329
Add custom column names to complete the field name mapping, and include `port` in GraphQL schema
> fix: add port and custom column names to pool_relay mapping

- docker-compose.yml
- packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
- packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/example_queries/stake_pools/allStakePoolFields.graphql
- packages/api-cardano-db-hasura/test/stakePool.query.test.ts
- packages/server/src/config.ts
`cardano-db-sync` is now storing the bech32 encoded Stake Pool ID, so this PR extends the API model to include it. There are also relationships being established through the raw stake pool hash, which was requiring a JOIN, when the table ID can be used. 
- Add `StakePool.id`
- Refactor the views to relate through the pool_hash.id
> Feature/Stake Pool ID

- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/example_queries/blocks/blockByNumber.graphql
- packages/api-cardano-db-hasura/src/example_queries/blocks/blockByNumbers.graphql
- packages/api-cardano-db-hasura/test/__snapshots__/blocks.query.test.ts.snap
- packages/api-cardano-db-hasura/test/blocks.query.test.ts
- packages/api-cardano-db-hasura/test/data_assertions/block_assertions.ts
The hex encoded value for blocl.vrf_key has been replaced with a bech32 encoded, CIP5 compliant string value. Since the old value is no longer stored, a breaking change is unavoidable. 
BREAKING CHANGE: `Block.vrfKey` is now a String not Hash32HexString, to
align with upstream changes in `cardano-db-sync`.
> fix: Change Block.vrfKey type to String

- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/example_queries/blocks/blocksByHashes.graphql
- packages/api-cardano-db-hasura/src/example_queries/transactions/aggregateDataWithinTransaction.graphql
- packages/api-cardano-db-hasura/src/example_queries/transactions/filteredAggregateDataWithinTransaction.graphql
- packages/api-cardano-db-hasura/src/example_queries/transactions/transactionsByHashesOrderByFee.graphql
- packages/api-cardano-db-hasura/src/executableSchema.ts
- packages/api-cardano-db-hasura/test/transactions.query.test.ts
- packages/util/src/scalars/Hash28Hex.ts
- packages/util/src/scalars/Hash32Hex.ts
- packages/util/src/scalars/index.ts
Closes #271 
Add a new type for 28 byte hex encoded hashes, refactor the existing to a better name, and revert https://github.com/input-output-hk/cardano-graphql/commit/9e28ffa6686fd28ea72a374c4eb45b0aa7b5efe9
**BREAKING CHANGES:**
- `Hash32HexString` -> `Hash32Hex`
- `Hash32HexString_comparison_exp` -> `Hash32Hex_comparison_exp`
- `SlotLeader.hash`, `StakePool.hash`, `StakePoolOwner.hash` are now `Hash28Hex` type
> fix: accurately allocate hashes to 28 byte type

- packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/example_queries/transactions/transactionByIdWithMetadataIfPresent.graphql
- packages/api-cardano-db-hasura/src/executableSchema.ts
- packages/api-cardano-db-hasura/test/__snapshots__/transactions.query.test.ts.snap
- packages/api-cardano-db-hasura/test/transactions.query.test.ts
`cardano-db-sync` is now maintaining a table of the transaction metadata, so this PR extends the API model to include it. 
`Transaction.metadata` contains an array of metadata if present in the transaction.
> feature: Transaction.metadata

- packages/server/src/config.ts
- packages/server/test/Server.test.ts
The config option WHITELIST_PATH was deprecated, but with the major version bump, it can be removed.
Remove support for WHITELIST_PATH
BREAKING CHANGE: WHITELIST_PATH is now ALLOW_LIST_PATH
> chore: Remove depreciated config option WHITELIST_PATH

- packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
- packages/api-cardano-db-hasura/test/blocks.query.test.ts
Closes #333
Just relax the limit so it shouldn't get in the way of most queries. Larger (or smaller) sets can still be paginated.
BREAKING CHANGE: Omitting the limit in queries will now return 2500 records, rather than 100
> chore: Change Hasura record limit from 100 to 2500

- nix/hasura-cli-ext/impure.nix
Updating the hasura-cli-ext tarball has after it has been bumped to the latest version.
> hasura-cli-ext: bump sha256 to current version

- packages/api-cardano-db-hasura/schema.graphql
Closes #390
Correct casing
```
Test Suites: 13 passed, 13 total
Tests:       42 passed, 42 total
Snapshots:   16 passed, 16 total
Time:        52.647 s
Ran all test suites matching /query/i.
Done in 54.78s.
> @cardano-graphql/cli
yarn run v1.22.5
$ NODE_ENV=test jest -c ./test/jest.config.js cli.test.ts --ci
PASS  test/cli.test.ts (14.943 s)
CLI Test
✓ Shows the program help if no arguments are passed (245 ms)
system-info command
✓ Logs an object useful during issue reporting (254 ms)
docker command
✓ Shows the program help if no arguments are passed (480 ms)
init
✓ writes a config file to the appropriate platform-specific path, scoped by command, copies a docker compose file to use as boilerplate, and handles secret generation (556 ms)
✓ can be used in automated processes using command …
```
> fix: casing on invalid hereafter in GraphQL schema

- packages/api-cardano-db-hasura/package.json
- packages/api-cardano-db-hasura/src/CardanoNodeClient.ts
- packages/api-cardano-db-hasura/src/HasuraClient.ts
- packages/api-cardano-db-hasura/src/executableSchema.ts
Fixes #248
Enabled by having direct access to `cardano-node` via `cardano-cli`, the node tip is used as the base value to determine the sync progress of `cardano-db-sync`. In addition, the initialisation state is now determined by asserting the most recent epoch in the table matches the tip's `epochNo`
> fix: Replaces the time-based logic to determine sync progress and initialisation state

- packages/api-cardano-db-hasura/src/CardanoCli.ts
- packages/api-cardano-db-hasura/src/Config.ts
- packages/server/src/CompleteApiServer.ts
- packages/server/src/config.ts
- packages/util/src/index.ts
- packages/util/src/knownEras.ts
- scripts/export_env.sh
to successfully cross an epoch boundary, the era needs to be determined dynamically
this change removes the static configuration.
Loop through eras, starting with the next protocol that will be transitioned to 
No longer set the ENV
> refactor: remove static era definition

- packages/api-cardano-db-hasura/src/example_queries/transactions/submitTransaction.graphql
It requires some returning value and `hash` is currently the only one :)
> Fix submitTransaction example

- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/executableSchema.ts
Despite the name, `JSONObject` was currently mapped to the underlying JSON resolver
as a workaround to avoid breaking changes.
BREAKING CHANGE: Transaction.metadata is now JSON type, not JSONObject
> chore: Correct Transaction.metadata type

- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/CardanoCli.ts
- packages/api-cardano-db-hasura/src/CardanoNodeClient.ts
- packages/api-cardano-db-hasura/src/HasuraClient.ts
- packages/api-cardano-db-hasura/src/example_queries/assets/assets.graphql
- packages/api-cardano-db-hasura/src/executableSchema.ts
- packages/api-cardano-db-hasura/test/__snapshots__/assets.query.test.ts.snap
- packages/api-cardano-db-hasura/test/ada.query.test.ts
- packages/api-cardano-db-hasura/test/assets.query.test.ts
- packages/api-cardano-db-hasura/test/stakePool.query.test.ts
- packages/api-cardano-db-hasura/test/util.ts
- packages/server/src/CompleteApiServer.ts
The benefit of the `cardano-cli` ledger state query is overshadowed by the resource demand. It's not a
supported interface, so was also always a risk for continual breaking changes.The total ada supply will be restored if the information can be accessed via an official API.
- Closes #435 
- Closes #440 
- Stop using the `cardano-cli` ledger-state query to access the reserves balance.
- Include rewards in the circulating supply calculation 
BREAKING CHANGE: AssetSupply.total is now an optional field, and will return null
> Chore/ Improve ada supply result, temporarily disable total supply to reduce resource demand

- packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
- packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/DataSyncController.ts
- packages/api-cardano-db-hasura/src/HasuraClient.ts
- packages/api-cardano-db-hasura/src/example_queries/assets/assets.graphql
- packages/api-cardano-db-hasura/test/assets.query.test.ts
A decision  was made to remove this property from asset metadata,
to revisit supporting the intent at a later stage.
- Remove the Asset.unit property, table column, and reference to it in the metadata server request.
- Improves the test to confirm the return response.
```
PASS  test/ada.query.test.ts
PASS  test/cardano.query.test.ts
PASS  test/stakeDeregistrations.query.test.ts
PASS  test/stakeRegistrations.query.test.ts
PASS  test/withdrawals.query.test.ts
PASS  test/assets.query.test.ts
PASS  test/transactions.query.test.ts
PASS  test/blocks.query.test.ts
PASS  test/genesis.query.test.ts
PASS  test/delegations.query.test.ts
PASS  test/rewards.query.test.ts
PASS  test/stakePool.query.test.ts (6.87 s)
PASS  test/paymentAddress.query.test.ts (13.121 s)
PASS  test/utxos.query.test.ts …
```
> chore: remove Asset.unit

- nix/nixos/graphql-engine-service.nix
- packages/api-cardano-db-hasura/hasura/docker-entrypoint.sh
Hasura is considered a private service in this stack. CORS is configured with
either the `cardano-graphql` server, or a reverse proxy if the former is not public.
Closes #392
Disable CORS when starting the Hasura `graphql-engine`. Use https://github.com/input-output-hk/cardano-graphql/wiki/Configuration#allowed_origins-string--regexp--string--regexp
> fix: disable CORS in Hasura graphql-engine

- packages/api-cardano-db-hasura/package.json
- packages/api-cardano-db-hasura/src/ChainFollower.ts
- packages/api-cardano-db-hasura/src/assetFingerprint.ts
- packages/api-cardano-db-hasura/src/index.ts
- packages/api-cardano-db-hasura/test/assetFingerprint.test.ts
Fixes: #487
- Pass empty string instead of `undefined` when `assetName` is not present.
- Verified using the CIP test vectors.
- Removes unnecessary jest scoping in `api-cardano-db-hasura` package script
> fix: assetFingerprint bug when no assetName present

- packages/api-cardano-db-hasura/schema.graphql
Enables filtering of epoch-related models, including rewards, by date range
> feature: add Epoch_bool_exp.startedAt

- .github/actions/cardano-node-ogmios_docker_sync/action.yml
- .github/workflows/node_sync.yml
- scripts/wait-for-sync.sh
This is preparation to complete the Jenkins migration to GitHub Actions. The local action will be replaced by a GitHub marketplace reference when available.
Uses cron-triggered workflow to maintain a `cardano-node` mainnet db cache, which can then be accessed in CI and other workflows. It can also be triggered manually.  
NA
> chore: adds a workflow to sync a cardano-node-ogmios to cache the db

- packages/api-cardano-db-hasura/src/CardanoNodeClient.ts
- packages/api-cardano-db-hasura/src/executableSchema.ts
User input errors need to be thrown from resolvers as a single `ApolloError`, but the Ogmios transaction submission client returns an array of errors that is currently not presented well. There is also some legacy logic left from a previous refactor to be cleaned up.
- removes legacy cardano-cli `isEraMismatch` logic
- reduces the array of errors from the Ogmios client to a single `ApolloError`,
with the individual errors mapped into the extension field.
Transaction submission errors are now present in the extensions eg:
``` json
{
"errors": [
{
"message": "Invalid Transaction",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"submitTransaction"
],
"extensions": {
"reasons": [
{
"name": "ValueNotConservedError",
"details": {
"consumed": {
"coins": 0,
"assets": {}
},
"produced": { …
```
> feature: submitTransaction error mapping

- packages/api-cardano-db-hasura/src/HasuraClient.ts
Fixes #542
Query
`{ cardanoDbMeta { syncPercentage }} `
was resulting in error for values like `100.0060734062478`
`{
"errors": [
{
"message": "Percentage must be a number between 0 - 100.00",
"locations": [
{
"line": 4,
"column": 5
}
],
"path": [
"cardanoDbMeta",
"syncPercentage"
],
"extensions": {
"code": "INTERNAL_SERVER_ERROR",
"exception": {
"stacktrace": [
"TypeError: Percentage must be a number between 0 - 100.00",
"    at GraphQLScalarType.serialize (/app/packages/util/dist/scalars/Percentage.js:15:19)",
"    at completeLeafValue (/app/node_modules/graphql/execution/execute.js:635:37)",
"    at completeValue (/app/node_modules/graphql/execution/execute.js:579:12)",
"    at completeValue (/app/node_modules/graphql/execution/execute.js:557:21)",
"    at completeValueCatchingError …
> Fix HasuraClient trying to return above 100%

- packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/example_queries/rewards/rewardsForAddress.graphql
- packages/api-cardano-db-hasura/test/rewards.query.test.ts
Closes #550 Closes #588 Closes #592
Includes all reward types in the Reward view.
BREAKING CHANGE: `Reward.stakePool` is now nullable to handle rewards of type
`treasury` or `reserves`.
> feature: include all reward types in Reward model, adds `type` field

- packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
- packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/example_queries/rewards/rewardsForAddress.graphql
- packages/api-cardano-db-hasura/src/example_queries/stake_pools/allStakePoolFields.graphql
- packages/api-cardano-db-hasura/test/rewards.query.test.ts
This is a column added to `cardano-db-sync` after the initial implementation here.
A new field to associate the epoch when the reward is included in the
account balance
.
> feature: `Reward.receivedIn`

- packages/api-cardano-db-hasura/test/__snapshots__/transactions.query.test.ts.snap
- packages/api-cardano-db-hasura/test/transactions.query.test.ts
Tests were refactored in https://github.com/input-output-hk/cardano-graphql/commit/17b9edecd2354261beed0f1f086f92caafb0c77f to use the _mainnet_ instead of _alonzo-purple_, but the assertion were not re-targeted. The Jest snapshot was updated to empty results since there were no results found.
Uses _mainnet_ transactions hashes, and update the Jest snapshot.
> test: fix test assertion for transactions with scripts

- packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
Asset tickers can now be up to 9 characters, but the view is limited to 5 based on the previous spec.
Increase the column definition from 5 to 9 chars
N.A.
> feature: support change to asset ticker length

- packages/api-cardano-db-hasura/src/MetadataClient.ts
https://github.com/input-output-hk/cardano-graphql/issues/670#issuecomment-1025991404
Define response as optional on error object
> fix(api-cardano-db-hasura): define response as optional in metadata server errors

- packages/server/src/config.ts
This fixes #712 and corrects the open PR #713, which seems to be unattended.
Strips whitespace from server credentials loaded from the docker-compose secrets.
> fix: trim whitespace from credentials in server config

- packages/api-cardano-db-hasura/schema.graphql
- packages/api-cardano-db-hasura/src/CardanoNodeClient.ts
- packages/api-cardano-db-hasura/src/HasuraClient.ts
- packages/server/src/index.ts
:pushpin: **fix!: Reward.receivedIn nullability**
Rewards are known before being "paid out", so not all rewards
have been received. This change fixes the model to ensure the
upcoming rewards have a nullable relationship to the epoch
received in.
:pushpin: **refactor!: remove remnants of previously deprecated config**
Two class constructor functions have now been updated to reflect
the deprecation of using the last configured major Cardano version,
which were missed in the previous breaking change. There are no
changes to the service config, so it will only impact library users.
> Fix: Nullable reward epoch received in + cleanup

- docker-compose.yml
- cardano-db-sync ignores SIGTERM, which is the default signal sent when stopping Docker containers
- Ogmios' `cardano-node-ogmios` sets this within the Dockerfile
https://github.com/CardanoSolutions/ogmios/blob/c32341e56ccbeb1cf1e803d4607699668a1e2cc2/Dockerfile#L73
> fix: gracefully shutdown cardano-db-sync

- docker-compose.yml
Pinning an unreleased state for _testnet_ compatibility, to work around the issue being discussed [here](https://github.com/CardanoSolutions/ogmios/pull/241#issuecomment-1198940107). The Docker tagging strategy has also changed for the better.
> chore: bump Ogmios to master HEAD

- packages/api-cardano-db-hasura/src/CardanoNodeClient.ts
- packages/api-cardano-db-hasura/src/ChainFollower.ts
- packages/api-cardano-db-hasura/src/Worker.ts
- packages/api-cardano-db-hasura/src/util.ts
- packages/server/src/index.ts
Ogmios disconnects the WebSocket when attempting to submit some invalid payloads. Once disconnected, the server must be restarted. There are also a couple of bugs with the connection context error and close handlers, causing a bunyan error.
- Hoist the context init to DRY the code.
- Fix the handlers to always log a structured object
- Treat `1006` close events as an error, the rest as informational.
- Shutdown and re-initialize the client on unexpected close events.
Example of the bunyan error:
```console
{"name":"cardano-graphql","hostname":"5fd0492a7031","pid":1,"level":30,"module":"Server","msg":"Initializing","time":"2022-09-08T09:13:13.201Z","v":0}
{"name":"cardano-graphql","hostname":"5fd0492a7031","pid":1,"level":30,"module":"HasuraClient","msg":"Initializing","time":"2022-09-08T09 …
```
> fix: Reconnect Ogmios sockets on unexpected disconnects, and logging fixes

- packages/api-cardano-db-hasura/package.json
- packages/server/src/Server.ts
- packages/util/package.json
- The `util` package depends on `set-interval-async`, but it's not explicitly defined.
- `Server.ts` has a duplicate line import statement for the same package.
- `api-cardano-db-hasura` has an unnecessary devDep 
- Add the explicit dependency
- Consolidate to as single imports
- Remove the devDep
> build: fix set-interval-async dependency

- Dockerfile
- flake.nix
- nix/cells/automation/pipelines.nix
- nix/nixos/cardano-graphql-background-service.nix
- nix/nixos/cardano-graphql-service.nix
- nix/nixos/graphql-engine-service.nix
- packages/api-cardano-db-hasura/src/HasuraBackgroundClient.ts
- packages/api-cardano-db-hasura/src/background.ts
* Updates for nixos services
* NixOS service changes to allow flake package import from the std cells
* Hasura cli extended path service related nixos service fixes
* Ogmios parameterization in cardano-graphql-background NixOS service
> Nixos service updates

- docker-compose.yml
Bumping the versions of db-sync and node to the newest releases. 
DB-sync: 13.2.0.2 
Node-Ogmios: 8.9.0
> feat: upgraded db-sync to 13.2.0.2 and node to 8.9.0

- docker-compose.yml
- packages/api-cardano-db-hasura/src/ChainFollower.ts
Added parsing safety for block. Taking care of having the right object to get the mints from.
> fix: added parsing depending on the block type for ChainFollower.ts

- packages/api-cardano-db-hasura/src/ChainFollower.ts
Chain follower starting from origin gets stuck on slot number 2138399 and adding assets to the Asset table does not start.
Adding a slot point just before the asset minting started so the chain follower can can resume at this point and start Asset syncing,
Added slot id and hash for the ogmios to find intersection to start
> Added ogmios slot point so that chain follower can start when the asset mint starts

- README.md
- docker-compose.yml
Upgrading db-sync to 13.4.0.0 this fixes an issue which leads to crashes when trying to sync up using a snapshot
> chore: upgraded db-sync

- Dockerfile
The url is not working anymore / no need for the PGDG
Remove the lines
> fix: remove background postgres client in dockerfile

- packages/api-cardano-db-hasura/src/example_queries/delegation_votes/delegationVotes.graphql
- packages/api-cardano-db-hasura/src/example_queries/delegation_votes/drepInfo.graphql
- packages/api-cardano-db-hasura/src/example_queries/stake_pools/queryDelegators.graphql
- packages/api-cardano-db-hasura/src/example_queries/stake_pools/stakePool_ActiveStake.graphql
Users, applications may want to query:
- The number of active stake ADA in a pool at a specific epoch
- How many delegators are delegating to a specific stake pool.
- Which dRep is the stake address being delegated to?
- Look up information about a dRep based on dRep name
Create 04 queries corresponding to the 04  needs above
No
> docs: adding 04 example queries (related to DREP, SPO) to example_queries folder
